### ISSUE TITLE
config_owner is undefined

### ISSUE THREAD

**Issue by sqrvrtx** [avnes/ansible-role-conky#1]
Running in Ubuntu Xenial with the following playbook:
---
- hosts: all
  roles:
    - avnes.ansible-role-conky

TASK [avnes.ansible-role-conky : Configure Conky] ******************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'config_owner' is undefined\n\nThe error appears to have been in '/etc/ansible/roles/avnes.ansible-role-conky/tasks/main.yml': line 58, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Configure Conky\n  ^ here\n"}

**Comment by avnes** [comment]
Fixed in tag v1.2
